export const tagStepperFr = {
  question1: "Quelles sont tes centres d'intérêts ? (choix multiple)",
  question2: "Quels sont tes passes-temps préférés (choix multiples)",
  question3:
    "Quelless sont tes sources de motivations à sortir de chez toi? (choix multiple)",
  question4: "Le weekend tu es plutot... (choix multiples)",
  question5: "Mot(s) d'ordre de la semaine",
  question6: "Le weekend parfait est fait pour... (choix multiple)",
  question7: "Quand aimes-tu sortir de ta caverne? ((choix multiple)",
  question8:
    "plusieurs évents dans la même journée? Combien d'events dans un weekend? ",
  question9: "Tu es plutôt...",
  question10: 'Comment decrirais-tu ton budget "kiff / loisirs"',
  question11: "Est-ce que tu es plutôt",
  question12: "Connais-tu ta personnalité MBTI? (texte d'explication)",
  question13: "Oui",
  question14: "Non",
  question15:
    "Si tu apprends qu'il ne te reste plus qu'une année à vivre, que changerais-tu à ta façon de vivre?",
  question16: "Quelle citation te parle le plus?",
  question17: "Quelle image te ressemble plus?",
  question18: "Pour finir, donne nous un fun fact sur toi stp",
  answer1: {
    a: "Cinéma",
    b: "Sport",
    c: "Peinture",
    d: "L'art",
    e: "Lecture",
    f: "Cuisine",
    g: "Méditation",
    h: "Politique",
    i: "Voyages/aventures",
    j: "Business",
  },
  answer2: {
    a: "sortir avec des potes",
    b: "aller au ciné",
    c: "aller au resto",
    d: "aller courir",
    e: "faire du sport",
    f: "regarder la tv",
    g: "jouer aux jeux vidéos",
    h: "Politique",
    i: "voyager dès que possible",
    j: "aller boire des coups",
  },
  answer3: {
    a: "Le fait d'etre célibataire",
    b: "J'ai la bougeote",
    c: "Mes potes",
    d: "J'aime bien boire et bien manger",
    e: "J'ai envie d'apprendre de nouvelles choses",
    f: "J'aime me depenser",
    g: "J'ai envie de rencontrer de nouvelles personnes",
    h: "L'envie de découvrir: lieux, personnes, concepts, métiers",
  },
  answer4: {
    a: "Netflix & Chill + Uber Eats",
    b: "Faire chaque jour quelque chose de nouveau - Never stop",
    c: "un weekend entre potes à boire des coups dans une maison avec piscine",
    d: " un saut à l'élastique depuis un pont dans le gard",
    e: "netflix/thé bien chaud sous le plaid",
    f: "un match de foot au stade et des pintes derrière",
    g: "un brunch entre filles le samedi midi",
  },
};
